### ISSUE TITLE
Page "Contact" / site Rivages

### ISSUE THREAD

**Issue by JustineGoy** [Fchallier/refonte-payot-rivages#11]
Hélène a quelques remarques sur la page "Contact" du site Rivages:
- baisser le corps de l'adresse et/ou mettre une Google Map à côté
- Manuscrits: mettre moins de blancs / organiser en deux colonnes
- améliorer la rubrique "Questions fréquentes"; la rendre plus belle
- Copyright (dans le footer) = 2017 et non 2015

**Comment by Fchallier** [comment]
- baisser le corps de l'adresse et/ou mettre une Google Map à côté - ok 
- Manuscrits: mettre moins de blancs / organiser en deux colonnes - ok
- Copyright (dans le footer) = 2017 et non 2015 - ok

**Comment by JustineGoy** [comment]
Merci !

Justine Goy

Service commercial
Éditions Payot & Rivages
18 rue Séguier, 75006 Paris
Tél : 01 44 41 39 62
j.goy@payotrivages.com<mailto:j.goy@payotrivages.com>
www.payot-rivages.fr<http://www.payot-rivages.fr/>


De : François [mailto:notifications@github.com]
Envoyé : mercredi 29 mars 2017 15:29
À : Fchallier/refonte-payot-rivages <refonte-payot-rivages@noreply.github.com>
Cc : Justine Goy <j.goy@payotrivages.com>; Author <author@noreply.github.com>
Objet : Re: [Fchallier/refonte-payot-rivages] Page "Contact" / site Rivages (#11)


  *   baisser le corps de l'adresse et/ou mettre une Google Map à côté - ok
  *   Manuscrits: mettre moins de blancs / organiser en deux colonnes - ok
  *   Copyright (dans le footer) = 2017 et non 2015 - ok

**Comment by Fchallier** [comment]
Je viens de faire un update pour les questions fréquentes tu me diras.
