### ISSUE TITLE
Footer trop gros

### ISSUE THREAD

**Issue by JustineGoy** [Fchallier/refonte-payot-rivages#2]
Le footer est trop gros (l'ensemble de la page, d'ailleurs?) sur Chrome
![image](https://cloud.githubusercontent.com/assets/26089123/23966717/bc6f2d7a-09bc-11e7-8319-7c081c2bc1e5.png)

**Comment by Fchallier** [comment]
Je pense que tu as fait un Zoom non  ? touche Ctrl+molette ? 

Car même chez moi,  sur un écran petit et sur Chrome le site s'affiche correctement... 

(Même réponse pour le problème #1 )
