### ISSUE TITLE
Je n'ai plus accès à mon espace admin

### ISSUE THREAD

**Issue by JustineGoy** [Fchallier/refonte-payot-rivages#3]
![image](https://cloud.githubusercontent.com/assets/26089123/23966760/e40d83ea-09bc-11e7-8146-8cca06f87634.png)

**Comment by Fchallier** [comment]
Voici les lien pour te connecter  : 
Pour rivages : [http://prod.payot-rivages.net/payot/users](http://prod.payot-rivages.net/payot/users)
Pour Payot : [http://prod.payot-rivages.net/payot/users](http://prod.payot-rivages.net/rivages/users)

Et le identifiants envoyé par mail.
