### ISSUE TITLE
Ordre des sous-univers / Catalogue Rivages

### ISSUE THREAD

**Issue by JustineGoy** [Fchallier/refonte-payot-rivages#7]
Hélène voudrait que les sous-univers soient dans l'ordre suivant:
Le Noir 
- Polars grand format
- Rivages Noir
- Ecrits Noirs
- Rivages Mystère 
- Revue Polar

Rivages Poche 
- Littérature
- Petite bibliothèque
- Rouge 

Autres collections
- Essais
- Philosophie
- Cinéma
- Jeunesse
- Tourisme & régions
- SF & Fantasy

**Comment by Fchallier** [comment]
C'est à jour
